name = "Andesite Age"
author = "thomasar"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8f5deb0a18abcea02531deaf3efafb23b76ae3b078619093debc0eb6ecac7bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
