name = "Andesite Age"
author = "thomasar"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a44db31d30a74b09fe9b17dc913b1ba35a799f374c202f1c39b283980d1675e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
